name: "davidkhala/build-push-action"
description: 'Release image from dockerfile to container registry'

branding:
  icon: 'package'
  color: 'blue'
inputs:
  registry:
    description: 'container registry'
    required: false
    default: ghcr.io
  working-directory:
    description: 'dirname of working directory'
    required: true
  password:
    description: 'docker login credential'
    required: true
  image:
    description: 'basename of container image'
    required: true
runs:
  using: "composite"
  steps:
  - uses: docker/login-action@master
    with:
      registry: ${{ inputs.registry }}
      username: ${{ github.actor }}
      password: ${{ inputs.password }}

  - uses: docker/metadata-action@master
    id: meta
    with:
      images: ${{ inputs.registry }}/${{ github.repository_owner }}/${{ inputs.image }}

  - uses: docker/build-push-action@master
    with:
      context: ${{ inputs.working-directory }}
      push: true
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
